{{- if .Values.ingress.enabled -}}
{{- $fullName := include "adhoc-odoo.serviceNameSuffix" . -}}
{{- $svcPort := .Values.service.port -}}
{{- $usewebsocket := .Values.odoo.performance.workers | toString | int -}}
{{- $odooVersion := include "adhoc-odoo.odoo-version" . | replace "." "" | int -}}
{{- $srvHttp := printf "%s-http" $fullName }}
{{- $srvWs := printf "%s-websocket" $fullName }}
{{- if .Values.ingress.reverseProxy.enabled }}
{{- $srvHttp = printf "%s-nginx" (include "adhoc-odoo.serviceNameSuffix" .) }}
{{- $srvWs = printf "%s-nginx" (include "adhoc-odoo.serviceNameSuffix" .) }}
{{- end }}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else -}}
apiVersion: extensions/v1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "adhoc-odoo.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.ingress.issuer | quote }}
    {{/* https://github.com/kubernetes/ingress-nginx/blob/master/docs/user-guide/nginx-configuration/annotations.md */}}
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/affinity: cookie
    {{/* en realidad vimos que no es necesario ya por defecto los pareciera levantar */}}
    nginx.ingress.kubernetes.io/websocket-services: {{ $fullName }}-websocket
    nginx.ingress.kubernetes.io/proxy-set-headers: "Upgrade=$http_upgrade;Connection=$connection_upgrade;"
    {{- if .Values.ingress.configurationSnippet.enabled }}
    nginx.ingress.kubernetes.io/configuration-snippet: |
{{- .Values.ingress.configurationSnippet.snippet | nindent 6 -}}
    {{- end }}
spec:
  ingressClassName: nginx
  tls:
    {{- if .Values.ingress.hosts }}
    {{- $hosts :=  regexSplit "," .Values.ingress.hosts -1}}
    {{- range $hosts}}
    - secretName: {{ . | quote }}
      hosts:
        - {{ . | quote }}
    {{- end }}
    {{- end }}
  rules:
    {{- if .Values.odoo.pg.db }}
    - host: "{{.Values.odoo.pg.db}}.{{.Values.ingress.cloudMainDomain}}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $srvHttp }}
                port:
                  number: 80
          {{- if gt $usewebsocket 0 }}
          - pathType: Prefix
            {{- if le $odooVersion 150 }}
            path: /longpolling
            {{- else }}
            path: /websocket
            {{- end  }}
            backend:
              service:
                name: {{ $srvWs }}
                port:
                  number: 80
          {{- end  }}
    {{- end  }}
    {{- if .Values.ingress.hosts }}
    {{- $hosts :=  regexSplit "," .Values.ingress.hosts -1}}
    {{- range $hosts }}
    - host: {{ . | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $srvHttp }}
                port:
                  number: 80
          {{- if gt $usewebsocket 0 }}
          - pathType: Prefix
            {{- if le $odooVersion 150 }}
            path: /longpolling
            {{- else }}
            path: /websocket
            {{- end  }}
            backend:
              service:
                name: {{ $srvWs }}
                port:
                  number: 80
          {{- end  }}
    {{- end }}
    {{- end }}
{{- end }}
