apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "adhoc-odoo.fullname" . }}
  labels:
    {{- include "adhoc-odoo.labels" . | nindent 4 }}
spec:
  {{- if or .Values.autoscaling.hpa.enabled .Values.autoscaling.keda.enabled }}
  maxUnavailable: 25%
  {{- else }}
  # Prevent disruptions in maintenance windows
  # (but we allow disruptions on small deployment with just one pod)
  {{- if lt (.Values.replicaCount | int) 3 }}
  maxUnavailable: 1
  {{- else }}
  maxUnavailable: 2
  {{- end }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "adhoc-odoo.selectorLabels" . | nindent 6 }}
      adhoc.ar/app-name: "odoo"
