annotations:
  category: DevOps
apiVersion: v2
name: adhoc-pods-cleanup
description: Dummy app for cleanup of "Terminated" pods (specially for preemptible nodes)

type: application

version: 0.1.0

appVersion: "1.0.0"

home: "https://github.com/adhoc-dev/helm-charts"
sources:
  - "https://github.com/adhoc-dev/"
maintainers:
  - name: dbollini
    email: dib@adhoc.com.ar

icon: "https://github.com/adhoc-dev/helm-charts/raw/master/img/vacuum-cleaner.png"
