apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: {{ include "adhoc-odoo.fullname" . }}
  namespace: {{ .Values.nameOverride }}
spec:
  template:
    spec:
      containers:
        - image: ghcr.io/knative/helloworld-go:latest
          env:
            - name: TARGET
              value: {{ .Values.odoo.saas.mode | quote }}
