# kind: StorageClass
# apiVersion: storage.k8s.io/v1
# metadata:
#   name: regionalpd-storageclass
#   labels:
#     {{- include "adhoc-pg.labels" . | nindent 4 }}
# provisioner: kubernetes.io/gce-pd
# parameters:
#   type: pd-standard
#   replication-type: regional-pd
# allowedTopologies:
#   - matchLabelExpressions:
#       - key: failure-domain.beta.kubernetes.io/zone
#         values:
#           - us-central1-b
#           - us-central1-c
# ---
# kind: PersistentVolumeClaim
# apiVersion: v1
# metadata:
#   name: {{ include "adhoc-pg.fullname" . }}-pvc
#   labels:
#     {{- include "adhoc-pg.labels" . | nindent 4 }}
# spec:
#   storageClassName: regionalpd-storageclass
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 300Gi