kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ include "adhoc-pg.fullname" . }}-sc
  labels:
    {{- include "adhoc-pg.labels" . | nindent 4 }}
provisioner: pd.csi.storage.gke.io
parameters:
  type: pd-standard
  replication-type: regional-pd
volumeBindingMode: WaitForFirstConsumer
allowedTopologies:
- matchLabelExpressions:
  - key: topology.gke.io/zone
    values:
    - southamerica-east1-a
    - southamerica-east1-b
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "adhoc-pg.fullname" . }}-sc
  labels:
    {{- include "adhoc-pg.labels" . | nindent 4 }}
spec:
  storageClassName: {{ include "adhoc-pg.fullname" . }}-sc
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
