{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "adhoc-odoo.serviceAccountName" . }}
  labels:
    {{- include "adhoc-odoo.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- with .Values.image.pullSecret }}
imagePullSecrets:
  - name: {{ . }}
{{- end }}
{{- end }}
