apiVersion: v1
kind: ConfigMap
metadata:
  name: ingress-nginx-controller
  namespace: nginx-ingress
data:
  enable-real-ip: "true"
  use-forwarded-headers: "true"
  use-proxy-protocol: "true"
  proxy-read-timeout: "720s"
  proxy-send-timeout: "720s"
  proxy-connect-timeout: "720s"
  ssl-redirect: "true"
  # client-max-body-size: "2m"
