{{- if .Values.ingress.reverseProxy.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "adhoc-odoo.fullname" . }}-nx
  labels:
    {{- include "adhoc-odoo.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "adhoc-odoo.nxselectorLabels" . | nindent 8 }}
{{- end }}