apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: adhoc-letsencrypt-staging-issuer
  namespace: cert-manager
spec:
  acme:
    # https://cert-manager.io/docs/configuration/acme/
    # The ACME server URL
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: {{ .Values.issuerEmail }}
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: {{ include "cert-cfg.fullname" . }}-letsencrypt-staging
    solvers:
    # Selector if not set, so the solver will be treated as the 'default' solver with the lowest priority.
    - selector: {}
      # https://cert-manager.io/docs/configuration/acme/http01/
      http01:
        ingress:
            class:  nginx
