apiVersion: v1
kind: Service
metadata:
  name: {{ include "adhoc-aeroo.fullname" . }}
  labels:
    {{- include "adhoc-aeroo.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: aero
      protocol: TCP
      name: aero
  selector:
    {{- include "adhoc-aeroo.selectorLabels" . | nindent 4 }}
