{{- if and .Values.cloudNativePG.enabled }}
{{- if eq .Values.cloudNativePG.persistence.storageClass "gcp-ssd" }}
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ include "adhoc-odoo.fullname" . }}-pg-sc
  labels:
    {{- include "adhoc-odoo.labels" . | nindent 4 }}
provisioner: pd.csi.storage.gke.io
parameters:
  # pd-ssd, pd-standard or pd-balanced
  type: pd-ssd
reclaimPolicy: Retain # TODO: Revisar
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
{{- end }}
{{- end }}
