apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "adhoc-defaultbackend.fullname" . }}-index
data:
  index.html: {{ print "|-" }}
  {{ range .Files.Lines "index.html" }}
    {{ . }}{{ end }}
  style.css: {{ print "|-" }}
  {{ range .Files.Lines "style.css" }}
    {{ . }}{{ end }}
  favicon.ico: {{ print "|-" }}
  {{ range .Files.Glob "favicon.ico" }}
    {{ . }}{{ end }}
  logo_adhoc.png: {{ print "|-" }}
  {{ range .Files.Glob "logo_adhoc.png" }}
    {{ . }}{{ end }}
  back_vector01.png: {{ print "|-" }}
  {{ range .Files.Glob "back_vector01.png" }}
    {{ . }}{{ end }}
