{{- if .Values.ingress.enabled -}}
{{- $fullName := include "adhoc-defaultbackend.fullname" . -}}
{{- $svcPort := 80 -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else -}}
apiVersion: networking.k8s.io/v1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "adhoc-defaultbackend.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
    - http:
        paths:
        - path: /
          pathType: "Prefix"
          backend:
#            serviceName: {{ include "adhoc-defaultbackend.fullname" . }}
#            servicePort: 80
            service:
              name: {{ include "adhoc-defaultbackend.fullname" . }}
              port:
                number: 80


{{- end }}
