annotations:
  category: DevOps
apiVersion: v2
name: cert-cfg
description: Default configurations for cert-manager

type: application

version: 0.1.2

appVersion: "1.0.0"

home: "https://github.com/adhoc-dev/helm-charts"
sources:
  - "https://github.com/adhoc-dev/"
maintainers:
  - name: dbollini
    email: dib@adhoc.com.ar
  - name: jjscarafia
    email: jjs@adhoc.com.ar

icon: "https://github.com/adhoc-dev/helm-charts/raw/master/img/kube-cert-manager-nginx-kubernetes.png"
