apiVersion: v1
description:
  The easy, open source way for everyone in your company to ask questions
  and learn from data.
name: metabasev2
version: 0.0.1
appVersion: v0.46.0
maintainers:
  - name: pmint93
    email: phamminhthanh69@gmail.com
home: http://www.metabase.com/
icon: http://www.metabase.com/images/logo.svg
sources:
  - https://github.com/metabase/metabase
