apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "adhoc-defaultbackend.fullname" . }}-index
data:
  index.html: {{ print "|-" }}
  {{ range .Files.Lines "index.html" }}
    {{ . }}{{ end }}
  style.css: {{ print "|-" }}
  {{ range .Files.Lines "style.css" }}
    {{ . }}{{ end }}
  favicon.ico: {{ "|-" }}
    {{  .Files.Get "favicon.ico" | b64enc }}
  logo_adhoc.png: {{  "|-" }}
    {{  .Files.Get "logo_adhoc.png"  | b64enc }}
  back_vector01.png: {{  "|-" }}
    {{  .Files.Get "back_vector01.png"  | b64enc }}

