{{- if .Values.cloudNativePG.enabled }}
# Network policies
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-same-namespace
spec:
  podSelector:
    matchLabels:
      cnpg.io/cluster: {{ include "adhoc-odoo.fullname" . }}-pg
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              adhoc.ar/app-name: "odoo"
        - podSelector:
            matchLabels:
              adhoc.ar/app-name: "odoo-fixdb"
        - podSelector:
            matchLabels:
              adhoc.ar/app-name: "odoo-wait-pg"

{{- end }}