apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "adhoc-defaultbackend.fullname" . }}-index
data:
  index.html: {{ print "|-" }}
  {{ range .Files.Lines "index.html" }}
    {{ . }}{{ end }}
