{{- if eq (include "keda.enabled" . | trim) "true" }}
{{- $isWakeupEnabled := eq (include "wakeupController.enabled" . | trim) "true" -}}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ .Release.Name }}
spec:
  scaleTargetRef:
    name: {{ include "adhoc-odoo.fullname" . }}
    kind: Deployment
    apiVersion: apps/v1
  minReplicaCount: {{ .Values.autoscaling.minReplicas | toString | int }}
  maxReplicaCount: {{ .Values.autoscaling.maxReplicas | toString | int }}
  initialCooldownPeriod: 900 # Initial period before scaling 15 min
  cooldownPeriod: 900
  triggers:
    {{- if and (eq (.Values.autoscaling.minReplicas | toString | int) 0) (not $isWakeupEnabled) }}
    - type: external-push
      metadata:
        scalerAddress: "keda-add-ons-http-external-scaler.keda:9090"
        interceptorRoute: {{ .Release.Name }}
    {{- else }}
    - type: prometheus
      metadata:
        serverAddress: http://prometheus-operated.monitoring.svc:9090
        metricName: odoo_istio_rps
        threshold: {{ .Values.autoscaling.keda.rpsThreshold | default 2 | quote }}
        query: |
          sum(rate(istio_requests_total{
            destination_workload_namespace="{{ .Release.Namespace }}",
            destination_app="adhoc-odoo",
            reporter="source"
          }[2m]))
    {{- end }}

{{- if and (eq (.Values.autoscaling.minReplicas | toString | int) 0) (not $isWakeupEnabled) }}
---
apiVersion: http.keda.sh/v1beta1
kind: InterceptorRoute
metadata:
  name: {{ .Release.Name }}
spec:
  target:
    {{- if .Values.ingress.reverseProxy.enabled }}
    service: {{ include "adhoc-odoo.serviceNameSuffix" . }}-nginx
    {{- else }}
    service: {{ include "adhoc-odoo.serviceNameSuffix" . }}-http
    {{- end }}
    port: 80
  # There is a bug in KEDA type discrepancy (CRD/admission accept string, but controller try to read a ServiceRef)
  # coldStart:
  #   fallback:
  #     service:
  #       name: default-http-server
  #     port: 80
  rules:
    - hosts:
      {{- if .Values.ingress.istio.enabled }}
      - {{ printf "%s.%s" .Values.odoo.pg.db .Values.ingress.istio.cloudMainDomain | quote }}
      {{- if .Values.ingress.istio.altHosts -}}
      {{- $hosts :=  regexSplit "," .Values.ingress.istio.altHosts -1 }}
      {{- range $hosts }}
      - {{ . | quote }}
      {{- end }}
      {{- end }}
      {{- end }}
  scalingMetric:
    # Scaling based on concurrent requests for a given target
    # Si los recursos son estables, es mejor usar concurrency ¿con workers?
    # concurrency:
    #   targetValue: 10 #  Target value for rate scaling

    # Scaling based on request rate for a given target
    # Util cuando las peticiones son cortas y queremos reaccionar a picos de tráfico. ¿website/sin workers?
    requestRate:
      granularity: 5s # Granularity for request rate scaling
      targetValue: 100 # Target value for request rate scaling
      window: 10s # Window for request rate scaling (Don't use more than 10s, otherwise it will problematic for the HPA)
{{- end }}
{{- end }}
