apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |
    user  nginx;
    worker_processes  1;

    error_log  /var/log/nginx/error.log;
    pid        /var/run/nginx.pid;

    events {
        worker_connections  1024;
    }


    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;

        log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                        '$status $body_bytes_sent "$http_referer" '
                        '"$http_user_agent" "$http_x_forwarded_for"';

        access_log  /var/log/nginx/access.log  main;

        sendfile        on;
        #tcp_nopush     on;

        keepalive_timeout  65;

        # mods que haceimos de manera global
        # Specifies the maximum accepted body size of a client request,
        # as indicated by the request header Content-Length.
        client_max_body_size 512M;
        server_names_hash_bucket_size 128;
        client_body_timeout 110;
        proxy_connect_timeout       7200;
        proxy_send_timeout          7200;
        send_timeout                7200;
        proxy_read_timeout 7200; #Defines a timeout for reading a response from the proxied server. The timeout is set only between two successive read operations, not for the

        include /etc/nginx/conf.d/*.conf;

        upstream odoo {
            server 127.0.0.1:8069;
        }
        upstream odoochat {
            server 127.0.0.1:8072;
        }
        map $http_upgrade $connection_upgrade {
            default upgrade;
            ''      close;
        }

        server {
            listen 80 default;
            proxy_read_timeout 720s;
            proxy_connect_timeout 720s;
            proxy_send_timeout 720s;

            # TODO revisar si los queremos sumar, odoo no los tiene
            # increase proxy buffer to handle some Odoo web requests
            # proxy_buffers 16 64k;
            # proxy_buffer_size 128k;

            # enable data compression
            gzip on;
            gzip_types text/css text/scss text/plain text/xml application/xml application/json application/javascript;
            # TODo revisar si los queremos mantener, no estan en docu de odoo
            # gzip_min_length 1100;
            # gzip_buffers 4 32k;
            # gzip_vary on;

            # force timeouts if the backend dies
            proxy_next_upstream error timeout invalid_header http_500 http_502 http_503;

            # Redirect requests to odoo backend server
            location / {
                # Add Headers for odoo proxy mode
                proxy_set_header X-Forwarded-Host $host;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                # proxy_set_header X-Forwarded-Proto $scheme;
                # forzamos https
                proxy_set_header X-Forwarded-Proto https;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_redirect off;
                proxy_pass http://odoo;

                # Enable HSTS
                add_header Strict-Transport-Security "max-age=31536000; includeSubDomains";
                # requires nginx 1.19.8
                proxy_cookie_flags session_id samesite=lax secure;
            }

            location /websocket {
                proxy_pass http://odoochat;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection $connection_upgrade;
                proxy_set_header X-Forwarded-Host $host;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                # proxy_set_header X-Forwarded-Proto $scheme;
                # forzamos https
                proxy_set_header X-Forwarded-Proto https;
                proxy_set_header X-Real-IP $remote_addr;
            }

            # TODO falta ver de incluir repositories ya sea haciendo enlaces simbolicos o iterando de alguna manera
            location ~ ^/[^/]+/static/.+$ {
                root /home/odoo/src;
                try_files /odoo/addons$uri /enterprise$uri @odoo;
                expires 24h;
            }

            # TODO ver si queremos este mas especifico para web siendo que odoo no lo tiene
            # cache some static data in memory for 60mins.
            # under heavy load this should relieve stress on the OpenERP web interface a bit.
            # location ~* /web/static/ {
            #     proxy_cache_valid 200 60m;
            #     proxy_buffering    on;
            #     expires 864000;
            #     proxy_pass http://odoo;
            # }

            # no usamos filestore
            # location /web/filestore {
            #     internal;
            #     alias /path/to/odoo/data-dir/filestore;
            # }

        }
    }
