{{- if .Values.metrics.podMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "adhoc-cluster-sentinel.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "adhoc-cluster-sentinel.labels" . | nindent 4 }}
    {{- with .Values.metrics.podMonitor.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "adhoc-cluster-sentinel.selectorLabels" . | nindent 6 }}
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
      interval: {{ .Values.metrics.podMonitor.interval }}
{{- end }}
