{{- if .Values.cloudNativePG.enabled }}

{{- if .Values.cloudNativePG.checkCRD }}
{{- $crd := lookup "apiextensions.k8s.io/v1" "CustomResourceDefinition" "cluster.postgresql.cnpg.io" "" -}}
{{- if not $crd }}
{{- fail (print "\nThe required CRD cluster.postgresql.cnpg.io is not installed in the cluster. Please install it first. \n\n helm repo add cnpg https://cloudnative-pg.github.io/charts \n helm upgrade --install cnpg \\ \n   --namespace cnpg-system \\ \n   --create-namespace \\ \n   cnpg/cloudnative-pg \n ") }}
{{- end }}
{{- end }}

{{- if not (or (eq .Values.cloudNativePG.restore.inTimeRecovery "latest") (eq .Values.cloudNativePG.restore.inTimeRecovery nil) (regexMatch "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}Z$" .Values.cloudNativePG.restore.inTimeRecovery)) }}
{{- fail "El valor de timestamp debe ser null, 'latest' o un timestamp UTC en el formato RFC3339 (YYYY-MM-DDTHH:MM:SSZ)." }}
{{- end }}

{{- end }}