{{- if and .Values.ingress.enabled (eq .Values.ingress.class "nginx") }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "registry-cache.fullname" . }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.ingress.issuer | quote }}
    nginx.ingress.kubernetes.io/whitelist-source-range: "{{ .Values.ingress.whitelistSourceRange | default "10.0.0.0/8" }}"
spec:
  ingressClassName: nginx
  # Empty TLS array to disable automatic TLS configuration and use the default cert
  tls: []
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "registry-cache.fullname" . }}
                port:
                  number: 5000
{{- end }}
{{- if and .Values.ingress.enabled (eq .Values.ingress.class "istio") }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name:  {{ include "registry-cache.fullname" . }}-vs
spec:
  hosts:
    - {{ .Values.ingress.host | quote }}
  gateways:
    # Reuse the baseline gateway created by the Istio Pulumi component.
    - istio-system/istio-internal-ingressgateway
  http:
    - route:
        - destination:
            host: {{ include "registry-cache.fullname" . }}
            port:
              number: 5000
{{- end }}
