{{- if and .Values.ingress.istio.enabled .Values.ingress.istio.logAll -}}
apiVersion: telemetry.istio.io/v1
kind: Telemetry
metadata:
  name: access-logging
spec:
  accessLogging:
    - providers:
        - name: envoy
      filter:
        # expression: response.code >= 400 || request.duration > 1000
        expression: 'true'  # Log all requests
  # To disable all logins: accessLogging: []
{{- end }}
