
{{- if .Values.ingress.istio.enabled -}}

{{- $fullName := include "adhoc-odoo.serviceNameSuffix" . -}}
{{- $svcPort := .Values.service.port -}}
{{- $usewebsocket := .Values.odoo.performance.workers | toString | int -}}
{{- $odooVersion := include "adhoc-odoo.odoo-version" . | replace "." "" | int -}}
{{- $srvHttp := printf "%s-http" $fullName }}
{{- $srvWs := printf "%s-websocket" $fullName }}
{{- $isKedaEnabled := eq (include "keda.enabled" . | trim) "true" -}}
{{- if .Values.ingress.reverseProxy.enabled }}
{{- $srvHttp = printf "%s-nginx" (include "adhoc-odoo.serviceNameSuffix" .) }}
{{- $srvWs = printf "%s-nginx" (include "adhoc-odoo.serviceNameSuffix" .) }}
{{- end }}

# Shared

apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ printf "%s-shared" .Values.odoo.pg.db | quote }}
spec:
  hosts:
    - {{ printf "%s.%s" .Values.odoo.pg.db .Values.ingress.istio.cloudMainDomain | quote }}
  gateways:
    - istio-system/istio-external-ingressgateway
    - istio-system/istio-internal-ingressgateway
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            {{- if $isKedaEnabled }}
            # Si KEDA está habilitado, enruta a través del interceptor para aprovechar el autoescalado basado en métricas de tráfico
            # Usamos siempre .svc.cluster.local para evitar problemas de resolución de DNS dentro del cluster, especialmente con KEDA
            # Aunque el verdadero sea .svc.cluster01.local por limitaciones de istio
            host: keda-add-ons-http-interceptor-proxy.keda.svc.cluster.local
            port:
              number: 8080
            {{- else }}
            host: {{ $srvHttp }}
            port:
              number: 80
            {{- end }}
      {{- if gt $usewebsocket 0 }}
    - match:
        - uri:
            {{- if le $odooVersion 150 }}
            prefix: /longpolling
            {{- else }}
            prefix: /websocket
            {{- end }}
      route:
        - destination:
            host: {{ $srvWs }}
            port:
              number: 80
      {{- end }}
{{ if .Values.ingress.istio.altHosts }}
---

{{- $hosts :=  regexSplit "," .Values.ingress.istio.altHosts -1 }}
{{- $secretName := printf "%s-custom-tls" .Values.odoo.pg.db | quote -}}
{{- $gwName := printf "%s-gateway" .Values.odoo.pg.db | quote -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ printf "%s-custom" .Values.odoo.pg.db | quote }}
spec:
  secretName: {{ $secretName }}
  dnsNames:
    {{- range $hosts }}
    - {{ . | quote }}
    {{- end }}
  issuerRef:
    name: {{ .Values.ingress.istio.issuer | quote }}
    kind: ClusterIssuer
  privateKey:
    rotationPolicy: Always
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ $gwName }}
spec:
  selector:
    istio: external-ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        {{- range $hosts }}
        - {{ . | quote }}
        {{- end }}
    - port:
        number: 443
        name: https
        protocol: HTTPS
      tls:
        mode: SIMPLE
        # Nombre del secreto TLS creado por cert-manager
        credentialName: {{ $secretName }}
      hosts:
        {{- range $hosts }}
        - {{ . | quote }}
        {{- end }}
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ printf "%s-custom" .Values.odoo.pg.db | quote }}
spec:
  hosts:
    {{- range $hosts }}
    - {{ . | quote }}
    {{- end }}
  gateways:
    - {{ $gwName }}
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            {{- if $isKedaEnabled }}
            # Si KEDA está habilitado, enruta a través del interceptor para aprovechar el autoescalado basado en métricas de tráfico
            # Usamos siempre .svc.cluster.local para evitar problemas de resolución de DNS dentro del cluster, especialmente con KEDA
            # Aunque el verdadero sea .svc.cluster01.local por limitaciones de istio
            host: keda-add-ons-http-interceptor-proxy.keda.svc.cluster.local
            port:
              number: 8080
            {{- else }}
            host: {{ $srvHttp }}
            port:
              number: 80
            {{- end }}
      retries:
        attempts: 10
        perTryTimeout: 5s
        retryOn: gateway-error,connect-failure,refused-stream
      {{- if gt $usewebsocket 0 }}
    - match:
        - uri:
            {{- if le $odooVersion 150 }}
            prefix: /longpolling
            {{- else }}
            prefix: /websocket
            {{- end }}
      route:
        - destination:
            host: {{ $srvWs }}
            port:
              number: 80
      {{- end }}

{{- end }}
{{- end }}