apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "adhoc-defaultbackend.fullname" . }}-nginx-config
data:
  nginx.conf: |
    events {
      worker_connections 1024;
    }
    http {
      include /etc/nginx/mime.types;
      default_type application/octet-stream;

      error_page 404 =200 /404.html;
      error_page 503 =200 /503.html;

      server {
        listen 80;
        server_name _;
        root /usr/share/nginx/html;

        location / {
          try_files $uri $uri/ /404.html;
        }
      }
    }
