{{- if and .Values.cloudNativePG.enabled }}
{{- if eq .Values.cloudNativePG.persistence.storageClass "gcp-ssd" }}
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ include "adhoc-odoo.fullname" . }}-pg-sc
  labels:
    {{- include "adhoc-odoo.labels" . | nindent 4 }}
provisioner: pd.csi.storage.gke.io
parameters:
  # pd-ssd, pd-standard or pd-balanced
  type: pd-ssd
#  replication-type: regional-pd
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
# allowedTopologies:
# - matchLabelExpressions:
#   - key: topology.gke.io/zone
#     values:
#     - southamerica-east1-a
#     - southamerica-east1-b
{{- end }}
{{- end }}