annotations:
  category: DevOps
apiVersion: v2
name: adhoc-odoo
description: Odoo Chart for v16+

type: application

version: 0.3.3

home: "https://github.com/adhoc-dev/helm-charts"
sources:
  - "https://github.com/adhoc-dev/"
maintainers:
  - name: dbollini
    email: dib@adhoc.inc
  - name: jjscarafia
    email: jjs@adhoc.inc
  - name: azacchino
    email: az@adhoc.inc

icon: "https://github.com/adhoc-dev/helm-charts/raw/master/img/Odoo_logo.svg"
