name: Release Helm Charts

concurrency: release-helm

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: 'src'
          ref: 'master'
          fetch-depth: 0

      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: 'dest'
          ref: 'gh-pages'
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v1

      - name: Update New Files and push to master branch
        shell: bash
        working-directory: src
        run: |
          for app in "./charts/"*; do
              if [[ -d $app ]]; then
                highest_version=$(ls -d $app/v* | sort -V | tail -n 1)
                helm package $highest_version -d ../dest/
              fi
          done
          helm repo index ../dest/ --url https://adhoc-dev.github.io/helm-charts/ --merge ../dest/index.yaml

      - name: Push New Files
        shell: bash
        working-directory: dest
        run: |
          git config user.name "helm"
          git config user.email "bot@adhoc.com"
          git add .
          git commit -m "Updated from ref: $GITHUB_SHA"
          git push