name: Release Helm Charts

concurrency: release-helm

permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'charts/**'
      - '.github/workflows/helm.yml'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          path: 'src'
          ref: 'main'
          fetch-depth: 0

      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          path: 'dest'
          ref: 'gh-pages'
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@fe7b79cd5ee1e45176fcad797de68ecaf3ca4814 # v4.2.0

      - name: Publish Helm Charts
        shell: bash
        working-directory: src
        run: |
          for app in "./charts/"*; do
              if [[ -d $app ]]; then
                if ! grep -q '^version:' "$app/Chart.yaml"; then
                    echo "No se pudo obtener la versión de $app, omitiendo."
                    continue
                fi
                helm package "$app" -d ../dest/
                echo "Creado paquete para $app"
              fi
          done
          helm repo index ../dest/ --url https://adhoc-dev.github.io/helm-charts/ --merge ../dest/index.yaml

      - name: Push New Files
        shell: bash
        working-directory: dest
        run: |
          git config user.name "helm"
          git config user.email "bot@adhoc.inc"
          git add .
          if git diff --cached --quiet; then
            echo "No hay cambios para pushear."
          else
            git commit -m "Updated from ref: $GITHUB_SHA"
            git push
          fi
