name: Backward compatibility

concurrency: release-helm

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'charts/**'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: 'src'
          ref: 'main'
          fetch-depth: 0

      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: 'dest'
          ref: 'master'
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v4.2.0

      - name: Update New Files and push to master branch
        shell: bash
        working-directory: src
        run: |
          for app in "./charts/"*; do
              if [[ -d $app ]]; then
                # Extrae la versión del Chart.yaml
                VERSION="v"$(grep '^version:' "$app/Chart.yaml" | awk '{print $2}')
                if [[ -z "$VERSION" ]]; then
                    echo "No se pudo obtener la versión de $app, omitiendo."
                    continue
                fi
                CHART_NAME=$(basename $app)
                rm -rf "../dest/charts/$CHART_NAME/$VERSION/"
                mkdir -p "../dest/charts/$CHART_NAME/$VERSION/"
                cp -R $app/* "../dest/charts/$CHART_NAME/$VERSION/"
              fi
          done
      - name: Push New Files
        shell: bash
        working-directory: dest
        run: |
          git config user.name "helm"
          git config user.email "bot@adhoc.inc"
          git add .
          if git diff --cached --quiet; then
            echo "No hay cambios para pushear."
          else
            git commit -m "Updated from ref: $GITHUB_SHA"
            git push
          fi
